
import argparse
from pathlib import Path
import numpy as np
import open3d as o3d


def find_obj_files(root_dir: Path):
    return sorted(root_dir.rglob("*.obj"))


def load_triangle_mesh(obj_path: Path):
    try:
        mesh = o3d.io.read_triangle_mesh(str(obj_path), enable_post_processing=False)
    except Exception as e:
        print(f"[WARN] 读取失败: {obj_path} | {e}")
        return None

    if mesh is None or mesh.is_empty():
        print(f"[WARN] 空网格: {obj_path}")
        return None

    vertices = np.asarray(mesh.vertices)
    triangles = np.asarray(mesh.triangles)

    if vertices.shape[0] == 0 or triangles.shape[0] == 0:
        print(f"[WARN] 顶点或面片为空: {obj_path}")
        return None

    return mesh


def estimate_num_points_from_spacing(mesh: o3d.geometry.TriangleMesh, spacing: float) -> int:
    """
    根据 mesh 表面积和目标间距估计采样点数：
        N ≈ surface_area / spacing^2
    """
    if spacing <= 0:
        raise ValueError("spacing 必须 > 0")

    vertices = np.asarray(mesh.vertices, dtype=np.float64)
    triangles = np.asarray(mesh.triangles, dtype=np.int64)

    v0 = vertices[triangles[:, 0]]
    v1 = vertices[triangles[:, 1]]
    v2 = vertices[triangles[:, 2]]

    areas = 0.5 * np.linalg.norm(np.cross(v1 - v0, v2 - v0), axis=1)
    total_area = float(np.sum(areas))

    n = max(1, int(total_area / (spacing * spacing)))
    return n


def sample_mesh_points(
    mesh: o3d.geometry.TriangleMesh,
    spacing: float,
    method: str = "uniform",
    poisson_init_factor: int = 5,
):
    """
    只采样表面点，不保留原始 mesh 顶点
    """
    n_points = estimate_num_points_from_spacing(mesh, spacing)

    if method == "uniform":
        pcd = mesh.sample_points_uniformly(number_of_points=n_points)
    elif method == "poisson":
        pcd = mesh.sample_points_poisson_disk(
            number_of_points=n_points,
            init_factor=poisson_init_factor,
        )
    else:
        raise ValueError(f"不支持的采样方式: {method}")

    pts = np.asarray(pcd.points, dtype=np.float64)
    return pts, n_points


def read_transformation_matrix(file_path: Path):
    file_path = Path(file_path)
    if not file_path.exists():
        return None

    with open(file_path, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f.readlines() if line.strip()]

    matrix = np.array([list(map(float, line.split())) for line in lines], dtype=np.float64)

    if matrix.shape != (4, 4):
        raise ValueError(f"变换矩阵尺寸错误，应为 4x4: {file_path}, 当前为 {matrix.shape}")

    return matrix


def compose_transformations(transform_dir: Path):
    """
    和第三个脚本保持一致：
    transform_manual.txt -> transform_icp.txt -> transform_refine.txt
    """
    transform_dir = Path(transform_dir)

    t_manual = read_transformation_matrix(transform_dir / "transform_manual.txt")
    t_icp = read_transformation_matrix(transform_dir / "transform_icp.txt")
    t_refine = read_transformation_matrix(transform_dir / "transform_refine.txt")

    T = np.eye(4, dtype=np.float64)

    if t_manual is not None:
        print("[INFO] transform with pair select")
        T = t_manual @ T

    if t_icp is not None:
        print("[INFO] transform with ICP")
        T = t_icp @ T

    if t_refine is not None:
        print("[INFO] transform with 2D feature match")
        T = t_refine @ T

    return T


def transform_points(points: np.ndarray, T: np.ndarray):
    """
    points: (N, 3)
    T: (4, 4)
    """
    if points.size == 0:
        return points.astype(np.float32)

    pts = np.asarray(points, dtype=np.float64)
    ones = np.ones((pts.shape[0], 1), dtype=np.float64)
    pts_h = np.concatenate([pts, ones], axis=1)
    pts_t = pts_h @ T.T
    return pts_t[:, :3].astype(np.float32)


class StructuredStreamingPlyWriter:
    """
    写成与第三个脚本一致的 xyzrgb structured binary PLY：
        float x, y, z
        uchar red, green, blue
    先写占位 header，最后回填真实点数。
    """
    def __init__(self, output_path: Path, default_color=(180, 180, 180)):
        self.output_path = Path(output_path)
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

        self.tmp_path = self.output_path.with_suffix(self.output_path.suffix + ".part")
        self.f = open(self.tmp_path, "wb")

        self.vertex_count = 0
        self.count_placeholder = "00000000000000000000"  # 固定20位

        self.default_color = tuple(int(x) for x in default_color)

        header = (
            "ply\n"
            "format binary_little_endian 1.0\n"
            "comment generated by sample_obj_to_ply_rgb.py\n"
            f"element vertex {self.count_placeholder}\n"
            "property float x\n"
            "property float y\n"
            "property float z\n"
            "property uchar red\n"
            "property uchar green\n"
            "property uchar blue\n"
            "end_header\n"
        )

        self.header_bytes = header.encode("ascii")
        self.count_offset = header.index(self.count_placeholder)

        self.f.write(self.header_bytes)
        self.f.flush()

        self.ply_dtype = np.dtype([
            ("x", "<f4"),
            ("y", "<f4"),
            ("z", "<f4"),
            ("red", "u1"),
            ("green", "u1"),
            ("blue", "u1"),
        ])

    def append_points(self, points: np.ndarray):
        if points is None or points.size == 0:
            return 0

        points = np.asarray(points)
        if points.ndim != 2 or points.shape[1] != 3:
            raise ValueError(f"points 形状应为 (N,3)，当前为 {points.shape}")

        pts32 = np.ascontiguousarray(points.astype(np.float32, copy=False))
        n = pts32.shape[0]

        arr = np.empty(n, dtype=self.ply_dtype)
        arr["x"] = pts32[:, 0]
        arr["y"] = pts32[:, 1]
        arr["z"] = pts32[:, 2]
        arr["red"] = self.default_color[0]
        arr["green"] = self.default_color[1]
        arr["blue"] = self.default_color[2]

        arr.tofile(self.f)

        self.vertex_count += n
        return n

    def finalize(self):
        self.f.flush()
        self.f.seek(self.count_offset)
        count_str = f"{self.vertex_count:020d}".encode("ascii")
        self.f.write(count_str)
        self.f.flush()
        self.f.close()
        self.tmp_path.replace(self.output_path)

    def abort(self):
        try:
            self.f.close()
        except Exception:
            pass

        if self.tmp_path.exists():
            try:
                self.tmp_path.unlink()
            except Exception:
                pass


def main():
    parser = argparse.ArgumentParser(
        description="对 OBJ 表面采样，只保留采样点，输出 xyzrgb structured binary PLY，并支持可选变换。"
    )
    parser.add_argument("input_dir", type=str, help="输入根目录（递归查找 *.obj）")
    parser.add_argument("output_ply", type=str, help="输出融合后的 ply 路径")

    parser.add_argument(
        "--spacing",
        type=float,
        required=True,
        help="表面采样目标间距，单位与 OBJ 坐标单位一致",
    )
    parser.add_argument(
        "--method",
        type=str,
        default="uniform",
        choices=["uniform", "poisson"],
        help="采样方式：uniform 或 poisson",
    )
    parser.add_argument(
        "--poisson-init-factor",
        type=int,
        default=5,
        help="Poisson 采样的 init_factor",
    )
    parser.add_argument(
        "--transform-dir",
        type=str,
        default=None,
        help="可选，包含 transform_manual.txt / transform_icp.txt / transform_refine.txt 的目录",
    )
    parser.add_argument(
        "--default-color",
        type=int,
        nargs=3,
        default=[180, 180, 180],
        help="输出 ply 的默认 RGB",
    )

    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output_ply = Path(args.output_ply)

    obj_files = find_obj_files(input_dir)
    if len(obj_files) == 0:
        print(f"[ERROR] 没有找到 OBJ 文件: {input_dir}")
        return

    T = None
    if args.transform_dir is not None:
        T = compose_transformations(Path(args.transform_dir))
        print("[INFO] 已启用坐标变换")

    print(f"[INFO] 共找到 {len(obj_files)} 个 OBJ 文件")
    print(f"[INFO] method = {args.method}")
    print(f"[INFO] spacing = {args.spacing}")
    print(f"[INFO] output_ply = {output_ply}")
    print(f"[INFO] default_color = {tuple(args.default_color)}")

    success_cnt = 0
    fail_cnt = 0
    total_written_points = 0

    writer = StructuredStreamingPlyWriter(
        output_path=output_ply,
        default_color=tuple(args.default_color),
    )

    try:
        for idx, obj_path in enumerate(obj_files, 1):
            print(f"\n[INFO] [{idx}/{len(obj_files)}] 处理: {obj_path}")

            mesh = load_triangle_mesh(obj_path)
            if mesh is None:
                print("[WARN] 跳过")
                fail_cnt += 1
                continue

            triangles = np.asarray(mesh.triangles)
            sampled_points, estimated_n = sample_mesh_points(
                mesh,
                spacing=args.spacing,
                method=args.method,
                poisson_init_factor=args.poisson_init_factor,
            )

            if T is not None:
                sampled_points = transform_points(sampled_points, T)

            print(f"[INFO] 三角面数: {triangles.shape[0]}")
            print(f"[INFO] 估计采样点数: {estimated_n}")
            print(f"[INFO] 实际采样点数: {sampled_points.shape[0]}")

            written_n = writer.append_points(sampled_points)
            total_written_points += written_n
            success_cnt += 1

            print(f"[INFO] 已追加写入点数: {written_n}")
            print(f"[INFO] 当前融合 ply 累计点数: {total_written_points}")

        writer.finalize()

        print("\n[INFO] 全部处理完成")
        print(f"[INFO] 成功: {success_cnt} 个 OBJ")
        print(f"[INFO] 失败: {fail_cnt} 个 OBJ")
        print(f"[INFO] 融合后的总点数: {total_written_points}")
        print(f"[INFO] 输出完成: {output_ply}")

    except Exception as e:
        writer.abort()
        raise RuntimeError(f"写入融合 PLY 失败: {e}") from e


if __name__ == "__main__":
    main()


"""

python sample_obj_to_ply.py yanghaitang/models/pc/0/terra_obj \
    yanghaitang/models/pc/sampled_recon.ply --spacing 0.116180
    
python sample_obj_to_ply.py nanfang/models/pc/0/terra_obj \
    nanfang/models/pc/sampled_recon.ply --spacing 0.121226

python sample_obj_to_ply.py xiaoxiang/models/pc/0/terra_obj \
    xiaoxiang/models/pc/sampled_recon.ply --spacing 0.115020

"""

